// var questions=[];
// questions[1]="";
// console.log(questions)
function questions(n)
{
	var question=[];
	question[1]="1、我喜欢把一件事情做完后再做另一件事。";
	question[2]="2、在工作中我喜欢独自筹划,不愿受别人干涉。";
	question[3]="3、在集体讨论中，我往往保持沉默。";
	question[4]="4、我喜欢做戏剧、音乐、歌舞、新闻采访等方面的工作。";
	question[5]="5、每次写信我都一挥而就，不再重复。";
	question[6]="6、我经常不停地思考某一问题，直到想出正确的答案。";
	question[7]="7、对别人借我的和我借别人的东西，我都能记得很清楚。";
	question[8]="8、我喜欢抽象思维的工作，不喜欢动手的工作。";
	question[9]="9、我喜欢成为人们注意的焦点。";
	question[10]="10、我喜欢不时地夸耀一下自己取得的好成就。";
	question[11]="11、我曾经渴望有机会参加探险。";
	question[12]="12、当我一个独处时，会感到更愉快。";
	question[13]="13、我喜欢在做事情前，对此事情做出细致的安排。";
	question[14]="14、我讨厌修理自行车、电器一类的工作。";
	question[15]="15、我喜欢参加各种各样的聚会。";
	question[16]="16、我愿意从事虽然工资少、但是比较稳定的职业。";
	question[17]="17、音乐能使我陶醉。";
	question[18]="18、我办事很少思前想后。";
	question[19]="19、我喜欢经常请示上级。";
	question[20]="20、我喜欢需要运用智力的游戏。";
	question[21]="21、我很难做那种需要持续集中注意力的工作。";
	question[22]="22、我喜欢亲自动手制作一些东西，从中得到乐趣。";
	question[23]="23、我的动手能力很差。";
	question[24]="24、和不熟悉的人交谈对我来说毫不困难。";
	question[25]="25、和别人谈判时，我总是很容易放弃自己的观点 ";
	question[26]="26、我很容易结识同性朋友。";
	question[27]="27、对于社会问题，我通常持中庸的态度。";
	question[28]="28、当我开始做一件事情后，即使碰到再多的困难，我也要执著地干下去。";
	question[29]="29、我是一个沉静而不易动感情的人。";
	question[30]="30、当我工作时，我喜欢避免干扰。";
	question[31]="31、我的理想是当一名科学家。";
	question[32]="32、与言情小说相比，我更喜欢推理小说。";
	question[33]="33、有些人太霸道，有时明明知道他们是对的，也要和他们对着干。";
	question[34]="34、我爱幻想。";
	question[35]="35、我总是主动地向别人提出自己的建议。";
	question[36]="36、我喜欢使用榔头一类的工具。";
	question[37]="37、我乐于解除别人的痛苦。";
	question[38]="38、我更喜欢自己下了赌注的比赛或游戏。";
	question[39]="39、我喜欢按部就班地完成要做的工作。";
	question[40]="40、我希望能经常换不同的工作来做。";
	question[41]="41、我总留有充裕的时间去赴约会。";
	question[42]="42、我喜欢阅读自然科学方面的书籍和杂志。";
	question[43]="43、如果掌握一门手艺并能以此为生，我会感到非常满意。";
	question[44]="44、我曾渴望当一名汽车司机。";
	question[45]="45、听别人谈“家中被盗”一类的事，很难引起我的同情。";
	question[46]="46、如果待遇相同，我宁愿当商品推销员，而不愿当图书管理员。";
	question[47]="47、我讨厌跟各类机械打交道。";
	question[48]="48、我小时候经常把玩具拆开，把里面看个究竟。";
	question[49]="49、当接受新任务后，我喜欢以自己的独特方法去完成它。";
	question[50]="50、我有文艺方面的天赋。";
	question[51]="51、我喜欢把一切安排得整整齐齐、井井有条。";
	question[52]="52、我喜欢作一名教师。";
	question[53]="53、和一群人在一起的时候，我总想不出恰当的话来说。";
	question[54]="54、看情感影片时，我常禁不住眼圈红润。";
	question[55]="55、我讨厌学数学。";
	question[56]="56、在实验室里独自做实验会令我寂寞难耐。";
	question[57]="57、对于急躁、爱发脾气的人，我仍能以礼相待。";
	question[58]="58、遇到难解答的问题时，我常常放弃。";
	question[59]="59、大家公认我是一名勤劳踏实的、愿为大家服务的人。";
	question[60]="60、我喜欢在人事部门工作。";

	return question[n];

}

function buttons(n)
{
var buttons=[];
	buttons[1]='<button class="answer" data-id="">是</button><button class="answer no" data-id="s">否</button>';
	buttons[2]='<button class="answer" data-id="r">是</button><button class="answer no" data-id="">否</button>';
	buttons[3]='<button class="answer" data-id="">是</button><button class="answer no" data-id="e">否</button>';
	buttons[4]='<button class="answer" data-id="a">是</button><button class="answer no" data-id="">否</button>';
	buttons[5]='<button class="answer" data-id="">是</button><button class="answer no" data-id="c">否</button>';
	buttons[6]='<button class="answer" data-id="i">是</button><button class="answer no" data-id="">否</button>';
	buttons[7]='<button class="answer" data-id="c">是</button><button class="answer no" data-id="">否</button>';
	buttons[8]='<button class="answer" data-id="i">是</button><button class="answer no" data-id="">否</button>';
	buttons[9]='<button class="answer" data-id="a">是</button><button class="answer no" data-id="">否</button>';
	buttons[10]='<button class="answer" data-id="a">是</button><button class="answer no" data-id="">否</button>';
	buttons[11]='<button class="answer" data-id="e">是</button><button class="answer no" data-id="">否</button>';
	buttons[12]='<button class="answer" data-id="">是</button><button class="answer no" data-id="s">否</button>';
	buttons[13]='<button class="answer" data-id="r">是</button><button class="answer no" data-id="">否</button>';
	buttons[14]='<button class="answer" data-id="">是</button><button class="answer no" data-id="r">否</button>';
	buttons[15]='<button class="answer" data-id="">是</button><button class="answer no" data-id="s">否</button>';
	buttons[16]='<button class="answer" data-id="">是</button><button class="answer no" data-id="e">否</button>';
	buttons[17]='<button class="answer" data-id="a">是</button><button class="answer no" data-id="">否</button>';
	buttons[18]='<button class="answer" data-id="">是</button><button class="answer no" data-id="c">否</button>';
	buttons[19]='<button class="answer" data-id="c">是</button><button class="answer no" data-id="">否</button>';
	buttons[20]='<button class="answer" data-id="i">是</button><button class="answer no" data-id="">否</button>';
	buttons[21]='<button class="answer" data-id="">是</button><button class="answer no" data-id="i">否</button>';
	buttons[22]='<button class="answer" data-id="r">是</button><button class="answer no" data-id="">否</button>';
	buttons[23]='<button class="answer" data-id="">是</button><button class="answer no" data-id="r">否</button>';
	buttons[24]='<button class="answer" data-id="e">是</button><button class="answer no" data-id="">否</button>';
	buttons[25]='<button class="answer" data-id="">是</button><button class="answer no" data-id="e">否</button>';
	buttons[26]='<button class="answer" data-id="s">是</button><button class="answer no" data-id="">否</button>';
	buttons[27]='<button class="answer" data-id="">是</button><button class="answer no" data-id="s">否</button>';
	buttons[28]='<button class="answer" data-id="e">是</button><button class="answer no" data-id="">否</button>';
	buttons[29]='<button class="answer" data-id="c">是</button><button class="answer no" data-id="">否</button>';
	buttons[30]='<button class="answer" data-id="i">是</button><button class="answer no" data-id="">否</button>';
	buttons[31]='<button class="answer" data-id="i">是</button><button class="answer no" data-id="">否</button>';
	buttons[32]='<button class="answer" data-id="">是</button><button class="answer no" data-id="a">否</button>';
	buttons[33]='<button class="answer" data-id="a">是</button><button class="answer no" data-id="">否</button>';
	buttons[34]='<button class="answer" data-id="a">是</button><button class="answer no" data-id="">否</button>';
	buttons[35]='<button class="answer" data-id="e">是</button><button class="answer no" data-id="">否</button>';
	buttons[36]='<button class="answer" data-id="r">是</button><button class="answer no" data-id="">否</button>';
	buttons[37]='<button class="answer" data-id="s">是</button><button class="answer no" data-id="">否</button>';
	buttons[38]='<button class="answer" data-id="e">是</button><button class="answer no" data-id="">否</button>';
	buttons[39]='<button class="answer" data-id="c">是</button><button class="answer no" data-id="">否</button>';
	buttons[40]='<button class="answer" data-id="">是</button><button class="answer no" data-id="c">否</button>';
	buttons[41]='<button class="answer" data-id="c">是</button><button class="answer no" data-id="">否</button>';
	buttons[42]='<button class="answer" data-id="i">是</button><button class="answer no" data-id="">否</button>';
	buttons[43]='<button class="answer" data-id="r">是</button><button class="answer no" data-id="">否</button>';
	buttons[44]='<button class="answer" data-id="">是</button><button class="answer no" data-id="r">否</button>';
	buttons[45]='<button class="answer" data-id="">是</button><button class="answer no" data-id="s">否</button>';
	buttons[46]='<button class="answer" data-id="e">是</button><button class="answer no" data-id="">否</button>';
	buttons[47]='<button class="answer" data-id="">是</button><button class="answer no" data-id="r">否</button>';
	buttons[48]='<button class="answer" data-id="">是</button><button class="answer no" data-id="r">否</button>';
	buttons[49]='<button class="answer" data-id="a">是</button><button class="answer no" data-id="">否</button>';
	buttons[49]='<button class="answer" data-id="a">是</button><button class="answer no" data-id="">否</button>';
	buttons[50]='<button class="answer" data-id="a">是</button><button class="answer no" data-id="">否</button>';
	buttons[51]='<button class="answer" data-id="c">是</button><button class="answer no" data-id="">否</button>';
	buttons[52]='<button class="answer" data-id="s">是</button><button class="answer no" data-id="">否</button>';
	buttons[53]='<button class="answer" data-id="">是</button><button class="answer no" data-id="s">否</button>';
	buttons[54]='<button class="answer" data-id="a">是</button><button class="answer no" data-id="">否</button>';
	buttons[55]='<button class="answer" data-id="">是</button><button class="answer no" data-id="i">否</button>';
	buttons[56]='<button class="answer" data-id="">是</button><button class="answer no" data-id="i">否</button>';
	buttons[57]='<button class="answer" data-id="c">是</button><button class="answer no" data-id="">否</button>';
	buttons[58]='<button class="answer" data-id="">是</button><button class="answer no" data-id="i">否</button>';
	buttons[59]='<button class="answer" data-id="s">是</button><button class="answer no" data-id="">否</button>';
	buttons[60]='<button class="answer" data-id="e">是</button><button class="answer no" data-id="">否</button>';

	return buttons[n];

}